### ISSUE TITLE
Only shaded relief (fjellskygge) is showing

### ISSUE THREAD

**Issue by turban** [kartverket/kartverket.vectortiles#2]
Hi, I'm testing this service for DNT - very nice that you work on vector tiles support! 

I'm testing this style URL with Maplibre GL: "https://cache.kartverket.no/test/styles/landtopo.json"

It only shows the shaded relief: 

<img width="994" alt="Screenshot 2021-12-09 at 16 13 51" src="https://user-images.githubusercontent.com/548708/145422695-219bcf25-d345-48ea-80df-4507fa84313b.png">

It seems that landtopo sprite and tiles are not available from cache.kartverket.no:

<img width="543" alt="Screenshot 2021-12-09 at 16 23 05" src="https://user-images.githubusercontent.com/548708/145424575-e436ca38-8508-480d-b1f0-9cfe40443fcb.png">

**Comment by tevbrasch** [comment]
I'm waiting for confirmation, but I believe this issue has now been solved. I've tested the service externally in several clients and all retrieve tiles without any issues.

**Comment by tevbrasch** [comment]
Unfortunately the problem has not been solved 100%, we'll comment back here when everything has been confirmed to be permanently fixed.

**Comment by tevbrasch** [comment]
Hi @turban, this issue has now been solved and the service is now working outside of Kartverkets network.

**Comment by turban** [comment]
Thanks! It has been a bit unstable the last days, but seems to load fine now on our testing site: https://turistforeningen.github.io/kartverket-vt/
