### ISSUE TITLE
Paths are missing on zoom 12

### ISSUE THREAD

**Issue by turban** [kartverket/kartverket.vectortiles#4]
Paths are showing from zoom 10, but missing on zoom 12: 

Example: https://turistforeningen.github.io/kartverket-vt/#12.13/60.57747/7.53496

![Screenshot 2021-12-15 at 14 41 01](https://user-images.githubusercontent.com/548708/146197099-7ecfd77d-8fe6-42b3-ab3e-3f7fe1c6014e.png)

![Screenshot 2021-12-15 at 14 41 13](https://user-images.githubusercontent.com/548708/146197134-90791fce-e9a2-44d7-81cf-d3b65c177825.png)

**Comment by Kajarnn** [comment]
@turban could you please test to see if the paths are present now on zoom 12? We reseeded the cache last night so this issue should be solved now. Thanks!

**Comment by turban** [comment]
I cab confirm that paths are now showing for all zoom levels from 10 - thanks for fixing!
